# Generated by Django 4.0.4 on 2022-05-17 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nbasystem', '0003_student_user_parent_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='pid',
            new_name='fid',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='sid',
        ),
    ]
