# Generated by Django 4.0.4 on 2022-05-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbasystem', '0005_remove_student_email_remove_student_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='lname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
