# Generated by Django 4.0.4 on 2022-05-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nbasystem', '0007_rename_fid_faculty_fname_rename_name_faculty_lname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='usernane',
            new_name='username',
        ),
    ]
