# Generated by Django 4.0.4 on 2022-05-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbasystem', '0008_rename_usernane_faculty_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('depcode', models.CharField(max_length=200, null=True)),
                ('sem', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='parent',
            name='fname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
