# Generated by Django 4.0.4 on 2022-05-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbasystem', '0010_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='CO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_no', models.IntegerField(blank=True, default=0, null=True)),
                ('desc', models.CharField(max_length=200, null=True)),
                ('cog_lvl', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no', models.IntegerField(blank=True, default=0, null=True)),
                ('desc', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PSO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pso_no', models.IntegerField(blank=True, default=0, null=True)),
                ('desc', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
